name: Build my application

on: push

jobs:
  build:
    name: Build out app
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Build API
        run: dotnet build
      - name: Build client
        run: ls
